last changes5

diff --git a/.github/workflows/blue-green.yaml b/.github/workflows/blue-green.yaml
--- a/.github/workflows/blue-green.yaml
+++ b/.github/workflows/blue-green.yaml
@@ -3,12 +3,10 @@ name: Blue-Green Deployment on EKS
 on:
   workflow_dispatch:
     inputs:
-      app:
-        description: 'App version to deploy (kickstart or scoops)'
+      version:
+        description: 'Version to deploy (v1 or v2)'
         required: true
-      image_tag:
-        description: 'Image tag to deploy (e.g. latest)'
-        required: true
+        default: 'v1'
 
 jobs:
   blue-green-deploy:
@@ -33,11 +31,23 @@ jobs:
       - name: Update kubeconfig
         run: aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME
 
-      - name: Deploy App (kickstart or scoops)
+      - name: Set App Based on Version
+        id: set-app
         run: |
-          FILE="deployment-${{ github.event.inputs.app }}.yaml"
-          IMAGE="${ECR_REPO}:${{ github.event.inputs.image_tag }}"
-          sed "s|<IMAGE>|$IMAGE|g" "$FILE" | kubectl apply -f -
+          if [ "${{ github.event.inputs.version }}" == "v1" ]; then
+            echo "app=kickstart" >> $GITHUB_OUTPUT
+          elif [ "${{ github.event.inputs.version }}" == "v2" ]; then
+            echo "app=scoops" >> $GITHUB_OUTPUT
+          else
+            echo "❌ Invalid version input (use v1 or v2)"
+            exit 1
+          fi
+
+      - name: Deploy App
+        run: |
+          FILE="deployment-${{ steps.set-app.outputs.app }}.yaml"
+          IMAGE="${ECR_REPO}:${{ steps.set-app.outputs.app }}"
+          sed "s|<IMAGE>|$IMAGE|g" $FILE | kubectl apply -f -
 
       - name: Wait for rollout to complete
         run: |
@@ -45,13 +55,15 @@ jobs:
 
       - name: Health Check
         run: |
-          POD=$(kubectl get pods -l app=version-update,version=${{ github.event.inputs.app }} -o jsonpath="{.items[0].metadata.name}")
+          POD=$(kubectl get pods -l app=version-update,version=${{ steps.set-app.outputs.app }} -o jsonpath="{.items[0].metadata.name}")
+          echo "Found pod: $POD"
           kubectl exec "$POD" -- curl -s localhost:80 || exit 1
 
-      - name: Switch Service to New Version
+      - name: Switch Service
         run: |
           kubectl patch service version-update-service \
-            -p "{\"spec\":{\"selector\":{\"app\":\"version-update\",\"version\":\"${{ github.event.inputs.app }}\"}}}"
+            -p "{\"spec\":{\"selector\":{\"app\":\"version-update\",\"version\":\"${{ steps.set-app.outputs.app }}\"}}}"
 
       - name: Show Ingress URL
-        run: kubectl get ingress -o wide || true
+        run: |
+          kubectl get ingress || true
